name: notebooks
channels:
  - defaults
dependencies:
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - statsmodels
  - gcem
  - libiconv
  - cython
  - ipycanvas
  - pyarrow
  - tensorflow
  - feedparser
  - sqlalchemy
  - ipython-sql
